const QACategories = {
    American: '英米',
    French: 'フランス',
    Spanish: 'スペイン',
    German: 'ドイツ',
    Chinese: '中国',
    InterCultural: '国際関係',
    jpLanguage: '国語国文',
    jpHistory: '歴史文化',
    eduDevelopmental: '教育発達',
    welfare: '社会福祉',
    nurse: '看護',
    infoScience: '情報科学',
    freshman: '新入生',
    graduateSchool: '大学院',
    culturalSubject: '教養科目',
    club: 'サークル',
    registration: '履修登録',
    laboratory: 'ゼミ・研究室',
    event: 'イベント',
    abroad: '留学',
    test: 'テスト',
    qualification: '資格・免許',
    jobHunting: '就活',
    service: '学内サービス',
    other: 'その他',
} as const
export default QACategories
